# Generated by Django 4.2.27 on 2026-01-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendarapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pos_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="위치 번호"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="위치 상세"
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calendarapp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="약품명")),
                (
                    "specification",
                    models.CharField(max_length=100, verbose_name="규격"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="보험코드")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="inventory.medicinelocation",
                        verbose_name="위치",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "specification", "location")},
            },
        ),
        migrations.CreateModel(
            name="MedicineStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="유통기한"),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="재고량")),
                (
                    "is_return_needed",
                    models.BooleanField(default=False, verbose_name="반품필요"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory.medicinemaster",
                        verbose_name="약품정보",
                    ),
                ),
            ],
        ),
    ]
