# Generated by Django 4.2.27 on 2026-02-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicineLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pos_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="위치번호"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="약품명")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="보험코드"
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="규격"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.medicinelocation",
                        verbose_name="위치",
                    ),
                ),
            ],
        ),
    ]
