# Generated by Django 4.2.27 on 2026-02-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicinemaster",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="medicinelocation",
            name="assigned_staff",
        ),
        migrations.RemoveField(
            model_name="medicinelocation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="medicinestock",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="medicinestock",
            name="is_return_needed",
        ),
        migrations.RemoveField(
            model_name="medicinestock",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="medicinelocation",
            name="pos_number",
            field=models.CharField(max_length=50, unique=True, verbose_name="위치번호"),
        ),
        migrations.AlterField(
            model_name="medicinemaster",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="보험코드"
            ),
        ),
        migrations.AlterField(
            model_name="medicinemaster",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.medicinelocation",
                verbose_name="위치",
            ),
        ),
        migrations.AlterField(
            model_name="medicinemaster",
            name="specification",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="규격"
            ),
        ),
        migrations.AlterField(
            model_name="medicinestock",
            name="medicine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="inventory.medicinemaster",
            ),
        ),
        migrations.AlterField(
            model_name="medicinestock",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="재고수량"),
        ),
    ]
