# Generated by Django 4.2.27 on 2026-02-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_medicinemaster_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MedicineStock",
        ),
    ]
