# Generated by Django 4.2.27 on 2026-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="leave_type",
            field=models.CharField(
                choices=[("월차", "월차"), ("반차", "반차"), ("휴가", "휴가")],
                max_length=10,
            ),
        ),
    ]
