# Generated by Django 4.2.27 on 2026-02-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0002_alter_event_leave_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "직원리스트", "verbose_name_plural": "직원리스트"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "휴가사용내역",
                "verbose_name_plural": "휴가사용내역",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=50, verbose_name="직원 성함"),
        ),
        migrations.AlterField(
            model_name="event",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarapp.employee",
                verbose_name="직원",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateField(verbose_name="사용일(종료)"),
        ),
        migrations.AlterField(
            model_name="event",
            name="leave_type",
            field=models.CharField(
                choices=[("월차", "월차"), ("반차", "반차"), ("휴가", "휴가")],
                max_length=10,
                verbose_name="휴가 종류",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateField(verbose_name="사용일(시작)"),
        ),
    ]
